version: "2.4"
services:
  neo4j:
    image: neo4j:4.0.0-enterprise
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./db/data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD-SHELL", "/wait-for-it.sh localhost:7474"]
      timeout: 2s
      interval: 10s
      retries: 20
      start_period: 30s
